# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Goclicu < Formula
  desc "A blazing fast terminal UI for ClickUp."
  homepage "https://github.com/PeterJohnBishop/goclicu"
  version "1.0.6"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/PeterJohnBishop/goclicu/releases/download/v1.0.6/goclicu_Darwin_x86_64.tar.gz"
      sha256 "4f942204c85593f1ab0e715f47defd2fc1c6e1e498a6f56a75bb65d83a1cb9c7"

      define_method(:install) do
        bin.install "goclicu"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/PeterJohnBishop/goclicu/releases/download/v1.0.6/goclicu_Darwin_arm64.tar.gz"
      sha256 "a9d0e0eb0360444dd7252fcb6d8898f02ab423647fac960ae9d7bf3bfa5bc966"

      define_method(:install) do
        bin.install "goclicu"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/PeterJohnBishop/goclicu/releases/download/v1.0.6/goclicu_Linux_x86_64.tar.gz"
      sha256 "a52d9a2c2ac656278698cfe1d84375f755ebb8ec69b86f7be97e8d576c37b5df"
      define_method(:install) do
        bin.install "goclicu"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/PeterJohnBishop/goclicu/releases/download/v1.0.6/goclicu_Linux_arm64.tar.gz"
      sha256 "b10c19f4d7ae4901ea4c4bcd641be391910be8d66809a0ff1f68687efbc4c1e7"
      define_method(:install) do
        bin.install "goclicu"
      end
    end
  end

  test do
    system "#{bin}/goclicu --version"
  end
end
