# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Goclicu < Formula
  desc "A blazing fast terminal UI for ClickUp."
  homepage "https://github.com/PeterJohnBishop/goclicu"
  version "1.0.7"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/PeterJohnBishop/goclicu/releases/download/v1.0.7/goclicu_Darwin_x86_64.tar.gz"
      sha256 "de0aefafb6dd6bbd169020a060a692a4205d6c4fd66eb4182927d93b6b5daecd"

      define_method(:install) do
        bin.install "goclicu"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/PeterJohnBishop/goclicu/releases/download/v1.0.7/goclicu_Darwin_arm64.tar.gz"
      sha256 "1f640d76cb0701de5fe793775a2ca9a5ff5001357cd3f1b3e014b5c11af38750"

      define_method(:install) do
        bin.install "goclicu"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/PeterJohnBishop/goclicu/releases/download/v1.0.7/goclicu_Linux_x86_64.tar.gz"
      sha256 "3d636e0e6e8c6067e98b3a06bc3a02eebbc331c9cf70dcd96b8dd80aa2e87484"
      define_method(:install) do
        bin.install "goclicu"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/PeterJohnBishop/goclicu/releases/download/v1.0.7/goclicu_Linux_arm64.tar.gz"
      sha256 "c18d9da6be7dc8f58af493625d800fbc84a5c497f05882600b5b691dc4aaec5b"
      define_method(:install) do
        bin.install "goclicu"
      end
    end
  end

  test do
    system "#{bin}/goclicu --version"
  end
end
